name: Pull Request

on:
  pull_request:

jobs:
  QA:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
         
      - name: Install Tools
        run: |
          pip install build twine
          
      - name: Build Sentiment3D Python package
        run: |
            python3 -m build

      - name: QA
        run: |
          twine check dist/* 
